# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$character"""

right_format = """
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo"""

### Left side

[battery]
disabled = true

[os]
disabled = false

[os.symbols]
Alpaquita = "[ ](fg:#85d888)"  # https://bell-sw.com/assets/images/media-kit/logo-alpaquita-labeled-black.svg
Alpine = "[ ](fg:#0d597f)"  # view-source:https://alpinelinux.org/alpinelinux-logo.svg
AlmaLinux = "[ ](fg:#86da2f)"  # view-source:https://upload.wikimedia.org/wikipedia/commons/1/13/AlmaLinux_Icon_Logo.svg
Amazon = "[ ](fg:#ff9900)"  # https://www.color-hex.com/color-palette/26593
Android = "[ ](fg:#3ddc84)"  # https://developer.android.com/distribute/marketing-tools/brand-guidelines
Arch = "[ ](fg:#1793d1)"  # view-source:https://archlinux.org/static/logos/archlinux-logo-dark-scalable.518881f04ca9.svg
Artix = "[ ](fg:#4cb6d8)"  # Picked from gradient in https://upload.wikimedia.org/wikipedia/commons/7/70/Artix_logo.svg
CachyOS = "[ ](fg:#00aa88)"  # view-source:https://upload.wikimedia.org/wikipedia/commons/b/b8/CachyOS_Logo.svg
CentOS = "[ ](fg:#a14f8c)"  # https://wiki.centos.org/ArtWork(2f)Brand(2f)Logo.html
Debian = "[ ](fg:#a80030)"  # view-source:https://www.debian.org/logos/openlogo-nd.svg
DragonFly = "[ ](fg:#cfff22)"  # Picked from circle in https://www.dragonflybsd.org/images/small_logo.png
Emscripten = "[ ](fg:#c1d72f)"  # https://github.com/emscripten-core/emscripten/blob/b31dd92a4b1b7a0cbdc1b1b3f4fb22e8a0726aea/media/logo.svg?short_path=912b905#L145
EndeavourOS = "[ ](fg:#7f3fbf)"  # https://forum.endeavouros.com/t/colour-palette/3480
Fedora = "[ ](fg:#51a2da)"  # https://docs.fedoraproject.org/en-US/project/brand/
FreeBSD = "[ ](fg:#eb0028)"  # https://freebsdfoundation.org/get-involved/brand-assets/
Garuda = "[󰛓 ](fg:#2886e8)"  # Picked from gradient in https://upload.wikimedia.org/wikipedia/commons/8/88/Garuda-blue-sgs.svg
Gentoo = "[ ](fg:#73d216)"  # https://wiki.gentoo.org/wiki/Project:Artwork/Colors
HardenedBSD = "[󰞌 ](fg:#2fbef2)"  # Picked from text in https://hardenedbsd.org/sites/default/files/2014-08-21_logo_small_03_0_0.png
Illumos = "[󰈸 ](fg:#ff430f)"  # view-source:https://illumos.org/docs/images/logo/PhoenixRGB.svg
Kali = "[ ](fg:#367bf0)"  # Normally white, but this blue is all over https://www.kali.org
Linux = "[ ](fg:#ffee11)"  # Yellow is Linus' favorite color. I picked a value.
Mabox = "[ ](fg:#32b557)"  # Picked from https://maboxlinux.org/wp-content/uploads/2018/12/3D_logo.png
Macos = "[ ](fg:#ffffff)"  # Apple is boring
Manjaro = "[ ](fg:#35bfa4)"  # Picked from https://forum.manjaro.org/uploads/default/original/3X/b/5/b56dfb8180e06711af1cbbebcc74c60208b15e7f.png
Mariner = "[ ](fg:#0078d4)"  # https://www.brandcolorcode.com/microsoft-azure
MidnightBSD = "[ ](fg:#ffffff)"  # Logo is B&W https://www.midnightbsd.org/
Mint = "[ ](fg:#87cf3e)"  # view-source:https://raw.githubusercontent.com/linuxmint/brand-logo/master/leaf-badge.svg
NetBSD = "[ ](fg:#f26711)"  # https://www.netbsd.org/images/README.tnflogo
NixOS = "[ ](fg:#7ebae4)"  # https://github.com/NixOS/nixos-artwork/blob/master/logo/README.md#colours
Nobara = "[ ](fg:#ffffff)"  # Logo is B&W https://nobaraproject.org/
OpenBSD = "[󰈺 ](fg:#ecdb78)"  # Picked from the fish in https://upload.wikimedia.org/wikipedia/en/thumb/8/83/OpenBSD_Logo_-_Cartoon_Puffy_with_textual_logo_below.svg/1024px-OpenBSD_Logo_-_Cartoon_Puffy_with_textual_logo_below.svg.png
openSUSE = "[ ](fg:#73ba25)"  # https://en.opensuse.org/openSUSE:Artwork_brand
OracleLinux = "[󰌷 ](fg:#c74634)"  # https://www.oracle.com/a/ocom/docs/oracle-brand-guidelines.pdf
Pop = "[ ](fg:#48b9c7)"  # view-source:https://upload.wikimedia.org/wikipedia/commons/4/46/Pop%21_OS_Icon.svg
Raspbian = "[ ](fg:#bc1142)"  # view-source:https://upload.wikimedia.org/wikipedia/en/c/cb/Raspberry_Pi_Logo.svg
Redhat = "[ ](fg:#ee0000)"  # https://www.redhat.com/en/about/brand/standards/color
RedHatEnterprise = "[ ](fg:#ee0000)"  # https://www.redhat.com/en/about/brand/standards/colorRockyLinux = "[ ](fg:foo)"
Redox = "[󰀘 ](fg:#ffffff)"  # Logo is B&W https://www.redox-os.org/
Solus = "[󰠳 ](fg:#5294e2)"  # Light blue in svg from https://getsol.us/branding/
SUSE = "[ ](fg:#30ba78)"  # https://brand.suse.com/design-language#color
Ubuntu = "[ ](fg:#77216f)"  # https://design.ubuntu.com/brand/colour-palette
Unknown = "[ ](fg:#6a5f7f)"  # Asked chatgpt: what's a good color to represent "unknown" in a neutral (non-negative) way on a dark background?
Void = "[ ](fg:#478061)"  # view-source:https://upload.wikimedia.org/wikipedia/commons/0/02/Void_Linux_logo.svg
Windows = "[󰍲 ](fg:#0078d4)"  # https://colorswall.com/palette/181955

[username]
format = '[$user]($style)@'

[hostname]
ssh_symbol = '🔒'
format = '[$ssh_symbol$hostname]($style):'


[directory]
truncate_to_repo = true
truncation_length = 3
format = "[$path]($style)"
truncation_symbol = "… /"

### Right side

[git_branch]
format = '[ $symbol$branch]($style)'

[git_commit]
format = '[ \($hash$tag\)]($style)'

[git_state]
format = ' \([$state( $progress_current/$progress_total)]($style)\)'

[git_metrics]
#disabled = false
format = '([ +$added]($added_style))([ -$deleted]($deleted_style))'

[git_status]
format = '( [\[$all_status$ahead_behind\]]($style))'

[hg_branch]

[package]
format = " is [$symbol$version]($style)"

[bun]
format = " via [$symbol]($style)"

[buf]
format = " via [$symbol]($style)"

[cmake]
format = " via [$symbol]($style)"

[cobol]
format = " via [$symbol]($style)"

[crystal]
format = " via [$symbol]($style)"

[daml]
format = " via [$symbol]($style)"

[dart]
format = " via [$symbol]($style)"

[deno]
format = " via [$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm)]($style)"

[elixir]
format = ' via [$symbol]($style)'

[elm]
format = ' via [$symbol]($style)'

[erlang]
format = ' via [$symbol]($style)'

[fennel]
format = ' via [$symbol]($style)'

[gleam]
format = ' via [$symbol]($style)'

[golang]
format = ' via [$symbol]($style)'

[gradle]
format = ' via [$symbol]($style)'

[haxe]
format = ' via [$symbol]($style)'

[helm]
format = ' via [$symbol]($style)'

[java]
format = ' via [$symbol]($style)'

[julia]
format = ' via [$symbol]($style)'

[kotlin]
format = ' via [$symbol]($style)'

[lua]
format = ' via [$symbol]($style)'

[meson]
format = ' via [$symbol]($style)'

[nim]
format = ' via [$symbol]($style)'

[nodejs]
format = ' via [$symbol]($style)'

[ocaml]
format = ' via [$symbol(\($switch_indicator$switch_name\))]($style)'

[opa]
format = ' via [$symbol]($style)'

[perl]
format = ' via [$symbol]($style)'

[php]
format = ' via [$symbol]($style)'

[pulumi]
format = ' via [$symbol$stack]($style)'

[purescript]
format = ' via [$symbol]($style)'

[python]
format = ' via [$symbol]($style)'

[quarto]
format = ' via [$symbol]($style)'

[raku]
format = ' via [$symbol]($style)'

[red]
format = ' via [$symbol]($style)'

[rlang]
format = ' via [$symbol]($style)'

[ruby]
format = ' via [$symbol]($style)'

[rust]
format = ' via [$symbol]($style)'

[solidity]
format = ' via [$symbol]($style)'

[typst]
format = ' via [$symbol]($style)'

[swift]
format = ' via [$symbol]($style)'

[vagrant]
format = ' via [$symbol]($style)'

[vlang]
format = ' via [$symbol]($style)'

[zig]
format = ' via [$symbol]($style)'
